### ISSUE TITLE
"Only draw calls using a single vertex buffer are supported"

### ISSUE THREAD

**Issue by 2u843yt385592yjh** [DarkStarSword/3d-fixes#10]
"Only draw calls using a single vertex buffer and a single index buffer are supported for now"
Please fix this blender addon error. It would take modding other games to **a whole new level.** We could use 3Dmigoto to mod even online games with barely any risk of a ban.

**Comment by DarkStarSword** [comment]
Support for this is now in the blender_multi_vbs_v3 branch. Consider this beta as it has only been very lightly tested and there is a moderate risk it might have broken something - please let me know if you are able to successfully use it, or run into any problems:

https://github.com/DarkStarSword/3d-fixes/blob/blender_multi_vbs_v3/blender_3dmigoto.py


Apologies that it has taken me so long to get around to this.

**Comment by DarkStarSword** [comment]
I have merged this into the master branch, so closing this ticket. If there are any regressions I'm sure someone will tell me soon enough.

**Comment by 2u843yt385592yjh** [comment]
I send here a zip file with a FrameAnalysis which supposedly contains a character's hair (from the game Tekken 7)
[FrameAnalysis-2023-12-13-154509.zip](https://github.com/DarkStarSword/3d-fixes/files/13662072/FrameAnalysis-2023-12-13-154509.zip)

The change you made fixes the issue and still works as intended.
However, I still can't import these problematic models successfully.

**Inside a problematic vb0 file**
![imagen](https://github.com/DarkStarSword/3d-fixes/assets/63649241/57318d13-2efb-4766-a2be-517b97104839)
Each element's SemanticName are not defined correctly or missing and appear as ATTRIBUTE. 
Perhaps this issue has to do with how 3DMigoto (or my mod manager) extracts the vb0 files. 

I have sometimes had success importing problematic models by manually renaming the vb0.
For example, if I open a vb0 file from a correct working extracted model, I noticed that the elements which have
"Format: R32G32B32_FLOAT" tend to have "SemanticName: TEXCOORD" instead of ATTRIBUTE

So I would manually rename elements with 
R32G32B32_FLOAT   to    TEXCOORD
R8G8B8A8_UNORM   to    UNORM
and so on, but this is very inconsistent.
